title: quickQuote
description: a tool for journalist to easily find and add video quotes to news articles
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
